DWAPlannerROS:
#Robot Config Params
  acc_lim_theta: 5.0
  acc_lim_x: 5.0
  acc_lim_y: 5.0
  acc_limit_trans: 5.0
  max_vel_x: 1.0
  min_vel_x: -1.0 
  max_vel_y: 1.0
  min_vel_y: -1.0
  max_trans_vel: 1.0
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.2
#Forward Simulation Parameters
  sim_time: 2
  sim_granularity: 0.05
  vx_samples: 15
  vy_samples: 15
  vth_samples: 0 
#Trajectory Scoring Parameters
  goal_distance_bias: 30.0
  path_distance_bias: 20.0
  occdist_scale: 0.01
  stop_time_buffer: 1
  forward_point_distance: 0.00
  scaling_speed: 0.2
  max_scaling_factor: 0.1
#Goal Tolerance Parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 3.14
  latch_xy_goal_tolerance: true
  rot_stopped_vel: 0.005
  trans_stopped_vel: 0.005
#Oscillation Prevention Param
  oscillation_reset_dist: 0.2
  oscillation_reset_angle: 0.2
#Global Plan PArameters
  prune_plan: false

recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]

