global_costmap:
  global_frame: /map
  robot_base_frame: base_link_dummy
  #Height and width of costmap

  resolution: 0.05
  transform_tolerance: 1
  update_frequency: 2.0
  publish_frequency: 2.0
  robot_radius: 0.45

  plugins:
  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer_laser, type: 'costmap_2d::ObstacleLayer'}
#  - {name: obstacle_layer_xtions, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  
  inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 0.70}
#  obstacle_layer_xtions:
#    observation_sources: front_point_cloud_sensor front_point_cloud_sensor2 back_point_cloud_sensor back_point_cloud_sensor2
#    track_unknown_space: true
#    enabled: true

  obstacle_layer_laser:
    observation_sources: laser_scan_sensor
    track_unknown_space: true
    enabled: true
    
  obstacle_layer_footprint: {enabled: true}
  
  static_layer: {enabled: true}
  static_map: true

