local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  
  height: 6
  width: 6
  rolling_window: true
  resolution: 0.025
  static_map: false
  transform_tolerance: 1
  update_frequency: 5.0
  publish_frequency: 5.0
  
  # Old footprint - no laser & a little off
  #footprint: [
  #  [-0.125, -0.25], [-0.125, -0.295],[0.125, -0.295], [0.125, -0.215], [0.075, -0.215], 
  #  [0.075, 0.215], [0.125, 0.215], [0.125, 0.295], [-0.125, 0.295], [-0.125, 0.25],
  #  [-0.525, 0.25], [-0.525, -0.25]
  #]
  footprint:  [[-0.125,-0.25],[-0.125,-0.295],[0.105,-0.295],[0.105,-0.115],[0.165,-0.115],[0.165,0.115],[0.105,0.115],[0.105,0.295],[-0.125,0.295],[-0.125,0.29],[-0.53,0.29],[-0.53,-0.25]]
  #footprint: [
  #  [-0.125, -0.25], [-0.125, -0.295], [0.105, -0.295], [0.105, -0.115], [0.165, -0.115], 
  #  [0.165, 0.115], [0.105, 0.115], [0.105, 0.295], [-0.125, 0.295], [-0.125, 0.25],
  #  [-0.465, 0.25], [-0.465, -0.25]
  #]
  
  plugins:
  - {name: obstacle_layer_xtions, type: 'costmap_2d::ObstacleLayer'}
  - {name: obstacle_layer_laser, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  
  inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 0.60}
  
  obstacle_layer_xtions:
    observation_sources: front_point_cloud_sensor front_point_cloud_sensor2 back_point_cloud_sensor back_point_cloud_sensor2
    #observation_sources: front_point_cloud_sensor front_point_cloud_sensor2
    enabled: true
    track_unknown_space: true
    combination_method: 0
  obstacle_layer_laser:
    observation_sources: laser_scan_sensor
    track_unknown_space: true
    enabled: true
  obstacle_layer_footprint: {enabled: true}

  

