## Round robot or edgy robot?
robot_radius: 0.2475
inflation_radius: 0.3

footprint: [[0.175,0.175],[0.175,-0.175],[-0.175,-0.175],[-0.175,0.175]]
footprint_padding: 0.03

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true, expected_update_rate: 0.5}



