global_costmap:
  global_frame: /map
  robot_base_frame: base_link

  resolution: 0.05
  static_map: true
  update_frequency: 2.0
  publish_frequency: 2.0
  footprint: [[0.24,0.17],[0.24,-0.17],[-0.24,-0.17],[-0.24,0.17]]
  footprint_padding: 0.01  
  plugins:
  - {name: map_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer_laser, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  
  inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 0.45}

  obstacle_layer_laser:
    observation_sources: laser_scan_sensor
    track_unknown_space: true
    enabled: true
  map_layer:
    track_unknown_space: true
    
  obstacle_layer_footprint: {enabled: true}
  

