map_type: costmap
#Footprint 
#1st row, top left wheel, and top right wheel and the top part
#2nd row, the right and the bottom part minus the castor wheels
#footprint: [[-0.125, -0.25], [-0.125, -0.295],[0.125, -0.295], [0.125, -0.215], [0.075, -0.215], 
#[0.075, 0.215], [0.125, 0.215], [0.125, 0.295], [-0.125, 0.295], [-0.125, 0.25],
#[-0.525, 0.25], [-0.525, -0.25]] 
# [0.125, 0.27], [-0.58, 0.22], [-0.58, -0.22] ]

#If robot_base frame is base_link dummy use below
#footprint: [ [0.35, -0.28], [0.35, 0.28], [-0.35, 0.25], [-0.35, -0.25] ]
inflation_radius: 0.46

obstacle_layer_xtions:
  back_point_cloud_sensor: {clearing: false, data_type: PointCloud2, expected_update_rate: 0.35, obstacle_range: 1.5, raytrace_range: 2.5, marking: true, min_obstacle_height: 0.2, sensor_frame: back_xtion_link, topic: back_xtion_voxel_grid/output}
  back_point_cloud_sensor2: {clearing: true, data_type: PointCloud2, expected_update_rate: 0.35, obstacle_range: 1.5, raytrace_range: 2.5, marking: false, min_obstacle_height: -0.1, sensor_frame: back_xtion_link, topic: back_xtion_voxel_grid/output}
  front_point_cloud_sensor: {clearing: false, data_type: PointCloud2, expected_update_rate: 0.35, obstacle_range: 2.5, raytrace_range: 3.5, marking: true, min_obstacle_height: 0.2, sensor_frame: front_xtion_link, topic: front_xtion_voxel_grid/output}
  front_point_cloud_sensor2: {clearing: true, data_type: PointCloud2, expected_update_rate: 0.35, obstacle_range: 2.5, raytrace_range: 3.5, marking: false, min_obstacle_height: -0.1, sensor_frame: front_xtion_link, topic: front_xtion_voxel_grid/output}

obstacle_layer_laser:
  laser_scan_sensor: {clearing: true, data_type: LaserScan, expected_update_rate: 0.3, marking: true, obstacle_range: 8, raytrace_range: 10, sensor_frame: laser, topic: scan}



