global_costmap:
  global_frame: /map
  robot_base_frame: base_footprint
  #Height and width of costmap

  resolution: 0.05
  transform_tolerance: 0.4
  update_frequency: 1.0
  publish_frequency: 2.0
  
  footprint:  [[-0.13,-0.295],[0.13,-0.295],[0.175,0.0],[0.13,0.295],[-0.13,0.296],
               [-0.535,0.25],[-0.535, -0.25] ] 
 # footprint_padding: 0.20

  plugins:
  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer_xtions, type: 'costmap_2d::ObstacleLayer'}
  - {name: obstacle_layer_laser, type: 'costmap_2d::ObstacleLayer'}

#  - {name: obstacle_layer_xtions, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  
  inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 0.5}
#  obstacle_layer_xtions:
#    observation_sources: front_point_cloud_sensor front_point_cloud_sensor2 back_point_cloud_sensor back_point_cloud_sensor2
#    track_unknown_space: true
#    enabled: true

  obstacle_layer_laser:
    observation_sources: laser_scan_sensor
    track_unknown_space: true
    enabled: true
    combination_method: 0
    
  obstacle_layer_footprint: {enabled: true}
  
  static_layer: {enabled: true}
  static_map: true

  obstacle_layer_xtions:
    observation_sources: front_point_cloud_sensor front_point_cloud_sensor2 back_point_cloud_sensor back_point_cloud_sensor2
    #observation_sources: front_point_cloud_sensor front_point_cloud_sensor2
    enabled: true
    track_unknown_space: true
    combination_method: 0
